:wrench: update .circleci/config.yml file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,6 +40,7 @@ jobs:
           command: |
             . venv/bin/activate
             sleep 1
+            flask db init
             flask db upgrade
       - run:
           name: flask test
@@ -61,7 +62,13 @@ jobs:
           command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
       - run:
           name: Smoke test
-          command: ./testbackend.sh
+          command: |
+          ./testbackend.sh
+          HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/api/articles`
+          if [ "$HTTPCODE" -ne 200 ];then
+            echo "heroku app not responding, failing deploy"
+            exit 1
+          fi
   buildandpush_dockerhub:
     docker:
       - image: docker:17.05.0-ce-git
